triggers:
  inbound_jms:
    type: "jms"
    options:
      username: "admin"
      host: "in2npdvdcssv03"
      port: "61613"
      queueName: "PYCAT_INBOUND"
      consumerCount: "1"
  planogram_scheduler:
    type: "scheduler"
    options:
      frequency: "Daily"
      time: "17:04"
  floorplan_scheduler:
    type: "scheduler"
    options:
      frequency: "Daily"
      time: "16:57"