---
Mappings:
- modelMapping:
    sourceModel: planogram
    targetModel: planogram
    fieldMapping:
    - targetField: documentActionCode
      default: "CHANGE_BY_REFRESH"
    - targetField: documentStatusCode
      default: "ORIGINAL"
    - sourceField: dbstatus
      targetField: dBStatus
    - sourceField: dbkey
      targetField: dBkey
    - sourceField: dbDateEffectiveFrom
      targetField: dBDateTimeEffectiveFrom
    segmentListMapping:
    - targetSegment: avpList
      fieldMapping:
      - targetField: name
        default: "DESC1"
      - targetField: value
        sourceField: desc1
    - targetSegment: avpList
      fieldMapping:
      - targetField: name
        default: "DESC2"
      - targetField: value
        sourceField: desc2
    - targetSegment: planogramProduct
      sourceSegment: product
      fieldMapping:
      - targetField: productIdentification
        sourceField: id
      segmentListMapping:
        - targetSegment: avpList
          fieldMapping:
          - targetField: name
            default: "DESC3"
          - targetField: value
            sourceField: desc3
    - targetSegment: planogramPerformance
      sourceSegment: performance
      fieldMapping:
      - targetField: maximumReplenishmentUnits
        sourceField: replenishmentMax
      - targetField: minimumReplenishmentUnits
        sourceField: replenishmentMin
      - targetField: dBParentProductKey
        sourceField : dbParentProductKey
      - targetField: dBKey
        sourceField : dbKey
    - targetSegment: planogramFixture
      sourceSegment: fixtures
      fieldMapping:
      - targetField: dBKey
        sourceField: dbKey
      - targetField: cubicSpace
        sourceField: cubic
      - targetField: locationIdentification
        sourceField: locationID